/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import codificacionfuente.*;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author super
 */
public class Aritmetica extends javax.swing.JFrame {

    /**
     * Creates new form aritmetica
     */
    public Aritmetica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mensaje = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        letra1 = new javax.swing.JTextField();
        letra2 = new javax.swing.JTextField();
        letra3 = new javax.swing.JTextField();
        letra4 = new javax.swing.JTextField();
        letra5 = new javax.swing.JTextField();
        letra6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        soloMensaje = new javax.swing.JRadioButton();
        conProbabilidad = new javax.swing.JRadioButton();
        error = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        porcentaje4 = new javax.swing.JTextField();
        porcentaje5 = new javax.swing.JTextField();
        porcentaje6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        porcentaje1 = new javax.swing.JTextField();
        porcentaje2 = new javax.swing.JTextField();
        porcentaje3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rangoLetras = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDecodificar = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Ingrese el mensaje");

        mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensajeActionPerformed(evt);
            }
        });

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Calcular)
                .addGap(37, 37, 37)
                .addComponent(Limpiar)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(Limpiar)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 153));

        jLabel2.setText("ps1");

        jLabel3.setText("ps2");

        jLabel4.setText("ps3");

        jLabel5.setText("ps4");

        jLabel6.setText("ps5");

        jLabel7.setText("ps6");

        letra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1ActionPerformed(evt);
            }
        });

        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });

        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });

        jLabel10.setText("El valor a codificar es: ");

        soloMensaje.setText("Solo Mensaje");
        soloMensaje.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soloMensajeStateChanged(evt);
            }
        });
        soloMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloMensajeActionPerformed(evt);
            }
        });

        conProbabilidad.setText("Con Probabilidad");

        error.setBackground(new java.awt.Color(255, 0, 51));
        error.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText(".");

        jLabel8.setText("Letra");

        porcentaje4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentaje4ActionPerformed(evt);
            }
        });

        porcentaje5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentaje5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Porcentaje");

        porcentaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentaje1ActionPerformed(evt);
            }
        });

        rangoLetras.setEditable(false);
        rangoLetras.setColumns(20);
        rangoLetras.setRows(5);
        jScrollPane1.setViewportView(rangoLetras);

        textDecodificar.setEditable(false);
        textDecodificar.setColumns(20);
        textDecodificar.setRows(5);
        jScrollPane2.setViewportView(textDecodificar);

        jLabel11.setText("El valor a codificar en binario es: ");

        jLabel12.setText("<= Final (1)");

        jLabel13.setText("inicio (0)=>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13)
                        .addGap(78, 78, 78)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel2)
                            .addGap(76, 76, 76)
                            .addComponent(jLabel3)
                            .addGap(73, 73, 73)
                            .addComponent(jLabel4)
                            .addGap(74, 74, 74)
                            .addComponent(jLabel5)
                            .addGap(68, 68, 68)
                            .addComponent(jLabel6)
                            .addGap(73, 73, 73)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentaje6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(conProbabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(soloMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(soloMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conProbabilidad))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentaje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentaje6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(50, 50, 50)))
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensajeActionPerformed

    private void letra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra1ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        a.clean();
        if (soloMensaje.isSelected() == true && conProbabilidad.isSelected() == true) {
            soloMensaje.setSelected(false);
            conProbabilidad.setSelected(false);
            error.setText("Solo elejir una opcion porfavor");
        } else {
            error.setText("");
        }

        
        if (soloMensaje.isSelected() == true) {
            a.addMensaje(mensaje.getText());
            a.iniciar(mensaje.getText());

            double cambio;

            if (a.linea.size() >= 1) {
                cambio = a.linea.get(0).elementAt(0);
                letra1.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(0).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje1.setText(String.valueOf(cambio));
            }
            if (a.linea.size() >= 2) {
                cambio = a.linea.get(1).elementAt(0);
                letra2.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(1).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje2.setText(String.valueOf(cambio));
            }
            if (a.linea.size() >= 3) {
                cambio = a.linea.get(2).elementAt(0);
                letra3.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(2).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje3.setText(String.valueOf(cambio));
            }
            if (a.linea.size() >= 4) {
                cambio = a.linea.get(3).elementAt(0);
                letra4.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(3).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje4.setText(String.valueOf(cambio));
            }
            if (a.linea.size() >= 5) {
                cambio = a.linea.get(4).elementAt(0);
                letra5.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(4).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje5.setText(String.valueOf(cambio));
            }
            if (a.linea.size() >= 6) {
                cambio = a.linea.get(5).elementAt(0);
                letra6.setText(String.valueOf((char) cambio));
                cambio = a.linea.get(5).elementAt(2) - a.linea.get(0).elementAt(1);
                porcentaje6.setText(String.valueOf(cambio));
            }

            //a.decBin(a.valorCodificar);
            rangoLetras.setText(a.getStringlinea());
            jLabel10.setText("El valor a codificar es: "+a.valorCodificar);
            jLabel11.setText("El valor a codificar en binario es: " + a.binarioDecimal(a.valorCodificar));
            a.decodificar(mensaje.getText());
            textDecodificar.setText(a.getStringDecodificar());

        } else if (conProbabilidad.isSelected() == true) {
//            a.addMensaje(mensaje.getText());
//            int count=a.linea.size();
//            a.clearlinea();
            if (letra1.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra1.getText().charAt(0), Double.valueOf(porcentaje1.getText()));
            }
            if (letra2.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra2.getText().charAt(0), Double.valueOf(porcentaje2.getText()));
            }
            if (letra3.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra3.getText().charAt(0), Double.valueOf(porcentaje3.getText()));
            }
            if (letra4.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra4.getText().charAt(0), Double.valueOf(porcentaje4.getText()));
            }
            if (letra5.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra5.getText().charAt(0), Double.valueOf(porcentaje5.getText()));
            }
            if (letra6.getText().isEmpty()==false) {
                a.addProbabilidad((double) letra6.getText().charAt(0), Double.valueOf(porcentaje6.getText()));
            }
      
            if (a.mayorA1 == true) {
                mensaje.setText("");
                error.setText("La probabilidad total da mayor a 1 \n vuelva a escribir los valores");
                letra1.setText("");
                letra2.setText("");
                letra3.setText("");
                letra4.setText("");
                letra5.setText("");
                letra6.setText("");
                porcentaje1.setText("");
                porcentaje2.setText("");
                porcentaje3.setText("");
                porcentaje4.setText("");
                porcentaje5.setText("");
                porcentaje6.setText("");
                a.clearlinea();
                a.mayorA1 = false;
            } else {
                error.setText("");
                a.iniciar(mensaje.getText());
                rangoLetras.setText(a.getStringlinea());
                jLabel10.setText("El valor a codificar es: " + a.valorCodificar);
                jLabel11.setText("El valor a codificar en binario es: "+a.binarioDecimal(a.valorCodificar));
                a.decodificar(mensaje.getText());
                textDecodificar.setText(a.getStringDecodificar());
            }
        }
        //intervalos.setText(a.getStringlinea1());
        repaint();
    }//GEN-LAST:event_CalcularActionPerformed

    private void soloMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soloMensajeActionPerformed

    private void soloMensajeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soloMensajeStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_soloMensajeStateChanged

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra4ActionPerformed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra5ActionPerformed

    private void porcentaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentaje4ActionPerformed

    private void porcentaje5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentaje5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentaje5ActionPerformed

    private void porcentaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentaje1ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        a.clean();
        porcentaje1.setText("");
        letra1.setText("");
        porcentaje2.setText("");
        letra2.setText("");
        porcentaje3.setText("");
        letra3.setText("");
        porcentaje4.setText("");
        letra4.setText("");
        porcentaje5.setText("");
        letra5.setText("");
        porcentaje6.setText("");
        letra6.setText("");
        mensaje.setText("");
        rangoLetras.setText("");
        textDecodificar.setText("");
        jLabel10.setText("El valor a codificar es: ");
        jLabel11.setText("El valor a codificar en binario es: ");
        error.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmetica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Limpiar;
    private javax.swing.JRadioButton conProbabilidad;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JTextField letra6;
    private javax.swing.JTextField mensaje;
    private javax.swing.JTextField porcentaje1;
    private javax.swing.JTextField porcentaje2;
    private javax.swing.JTextField porcentaje3;
    private javax.swing.JTextField porcentaje4;
    private javax.swing.JTextField porcentaje5;
    private javax.swing.JTextField porcentaje6;
    private javax.swing.JTextArea rangoLetras;
    private javax.swing.JRadioButton soloMensaje;
    private javax.swing.JTextArea textDecodificar;
    // End of variables declaration//GEN-END:variables


CodificacionAritmetica a = new CodificacionAritmetica();
public void paint(Graphics g) {
        super.paint(g);
        float total=0;
        float valor=0;
        int l=0;

        if(true) 
        {
            for(int i=0; i<a.linea.size();i++)
            {
               valor=(float) (a.linea.get(i).elementAt(2)-a.linea.get(i).elementAt(1));
               total= valor+total; 
            }
            
            for(int j=0; j<a.linea.size();j++)
            {
                valor= (float)(a.linea.get(j).elementAt(2)-a.linea.get(j).elementAt(1));

                int L= Math.round(valor*400 /total);
                
                double R=Math.random()*255;
                double G=Math.random()*255;
                double B=Math.random()*255;
                //System.out.println("lllllllllllllllllllllllllllllllll  "+valor);
                g.setColor(new Color((int)R,(int)G,(int)B));
                g.fillRect(350+l,350,L,30);//horizontal, vertical, largo, alto
                
                g.setColor(Color.WHITE);
                
                g.drawString( (" [ " + a.linea.get(j).elementAt(1) + " , " + a.linea.get(j).elementAt(2) + " ) "),360+l,370);
                l=(L+l);  
            }
        }
    }
}


